/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { IconType } from "./components/pvr-icon/icon-type";
export { IconType } from "./components/pvr-icon/icon-type";
export namespace Components {
    interface PvrButton {
        "border": boolean;
        "disabled": boolean;
        "icon": IconType | null;
        "size": "small" | "normal" | "large";
        "type": "primary" | "secondary" | "silent" | "red";
    }
    interface PvrComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface PvrIcon {
        /**
          * The role of the button
         */
        "type": IconType;
    }
    interface PvrInput {
        "icon"?: IconType;
        "placeholder"?: string;
    }
}
export interface PvrInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPvrInputElement;
}
declare global {
    interface HTMLPvrButtonElement extends Components.PvrButton, HTMLStencilElement {
    }
    var HTMLPvrButtonElement: {
        prototype: HTMLPvrButtonElement;
        new (): HTMLPvrButtonElement;
    };
    interface HTMLPvrComponentElement extends Components.PvrComponent, HTMLStencilElement {
    }
    var HTMLPvrComponentElement: {
        prototype: HTMLPvrComponentElement;
        new (): HTMLPvrComponentElement;
    };
    interface HTMLPvrIconElement extends Components.PvrIcon, HTMLStencilElement {
    }
    var HTMLPvrIconElement: {
        prototype: HTMLPvrIconElement;
        new (): HTMLPvrIconElement;
    };
    interface HTMLPvrInputElementEventMap {
        "pvrKeyPress": any;
    }
    interface HTMLPvrInputElement extends Components.PvrInput, HTMLStencilElement {
        addEventListener<K extends keyof HTMLPvrInputElementEventMap>(type: K, listener: (this: HTMLPvrInputElement, ev: PvrInputCustomEvent<HTMLPvrInputElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLPvrInputElementEventMap>(type: K, listener: (this: HTMLPvrInputElement, ev: PvrInputCustomEvent<HTMLPvrInputElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLPvrInputElement: {
        prototype: HTMLPvrInputElement;
        new (): HTMLPvrInputElement;
    };
    interface HTMLElementTagNameMap {
        "pvr-button": HTMLPvrButtonElement;
        "pvr-component": HTMLPvrComponentElement;
        "pvr-icon": HTMLPvrIconElement;
        "pvr-input": HTMLPvrInputElement;
    }
}
declare namespace LocalJSX {
    interface PvrButton {
        "border"?: boolean;
        "disabled"?: boolean;
        "icon"?: IconType | null;
        "size"?: "small" | "normal" | "large";
        "type"?: "primary" | "secondary" | "silent" | "red";
    }
    interface PvrComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface PvrIcon {
        /**
          * The role of the button
         */
        "type"?: IconType;
    }
    interface PvrInput {
        "icon"?: IconType;
        "onPvrKeyPress"?: (event: PvrInputCustomEvent<any>) => void;
        "placeholder"?: string;
    }
    interface IntrinsicElements {
        "pvr-button": PvrButton;
        "pvr-component": PvrComponent;
        "pvr-icon": PvrIcon;
        "pvr-input": PvrInput;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "pvr-button": LocalJSX.PvrButton & JSXBase.HTMLAttributes<HTMLPvrButtonElement>;
            "pvr-component": LocalJSX.PvrComponent & JSXBase.HTMLAttributes<HTMLPvrComponentElement>;
            "pvr-icon": LocalJSX.PvrIcon & JSXBase.HTMLAttributes<HTMLPvrIconElement>;
            "pvr-input": LocalJSX.PvrInput & JSXBase.HTMLAttributes<HTMLPvrInputElement>;
        }
    }
}
