/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { IconType } from "./components/pvr-icon/icon-type";
export { IconType } from "./components/pvr-icon/icon-type";
export namespace Components {
    interface PvrButton {
        "border": boolean;
        "disabled": boolean;
        "icon": IconType | null;
        "size": "small" | "normal" | "large";
        "type": "primary" | "secondary" | "silent" | "warning" | "red";
    }
    interface PvrComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface PvrIcon {
        /**
          * The role of the button
         */
        "type": IconType;
    }
}
declare global {
    interface HTMLPvrButtonElement extends Components.PvrButton, HTMLStencilElement {
    }
    var HTMLPvrButtonElement: {
        prototype: HTMLPvrButtonElement;
        new (): HTMLPvrButtonElement;
    };
    interface HTMLPvrComponentElement extends Components.PvrComponent, HTMLStencilElement {
    }
    var HTMLPvrComponentElement: {
        prototype: HTMLPvrComponentElement;
        new (): HTMLPvrComponentElement;
    };
    interface HTMLPvrIconElement extends Components.PvrIcon, HTMLStencilElement {
    }
    var HTMLPvrIconElement: {
        prototype: HTMLPvrIconElement;
        new (): HTMLPvrIconElement;
    };
    interface HTMLElementTagNameMap {
        "pvr-button": HTMLPvrButtonElement;
        "pvr-component": HTMLPvrComponentElement;
        "pvr-icon": HTMLPvrIconElement;
    }
}
declare namespace LocalJSX {
    interface PvrButton {
        "border"?: boolean;
        "disabled"?: boolean;
        "icon"?: IconType | null;
        "size"?: "small" | "normal" | "large";
        "type"?: "primary" | "secondary" | "silent" | "warning" | "red";
    }
    interface PvrComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface PvrIcon {
        /**
          * The role of the button
         */
        "type"?: IconType;
    }
    interface IntrinsicElements {
        "pvr-button": PvrButton;
        "pvr-component": PvrComponent;
        "pvr-icon": PvrIcon;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "pvr-button": LocalJSX.PvrButton & JSXBase.HTMLAttributes<HTMLPvrButtonElement>;
            "pvr-component": LocalJSX.PvrComponent & JSXBase.HTMLAttributes<HTMLPvrComponentElement>;
            "pvr-icon": LocalJSX.PvrIcon & JSXBase.HTMLAttributes<HTMLPvrIconElement>;
        }
    }
}
